name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main # Trigger this workflow on pushes to the 'main' branch

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install # Replace with 'yarn install' if using yarn

      - name: Build project
        run: npm run build # Replace this with your project's build command

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./build # Replace 'build' with your output directory if different
